[book]
title = "Bevy REPL Book"
authors = ["Philip Linden"]
language = "en"
multilingual = false
src = "doc/src"

[build]
build-dir = "doc/book/"
create-missing = false

[output.html]
# Link back to the repository
git-repository-url = "https://github.com/philiplinden/bevy_repl"
# Needed so relative links work when hosted at https://<user>.github.io/bevy_repl/
site-url = "/bevy_repl/"

[output.html.fold]
enable = false # whether or not to enable section folding
level = 1      # the depth to start folding
